services:
  prometheus:
    image: prom/prometheus
    ports:
      - '49090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    develop:
      watch:
        - path: ./tunnel/config
          action: rebuild
  grafana:
    image: grafana/grafana
    ports:
      - '43000:3000'
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashborad.yml
      - ./grafana/isucon.json:/var/lib/grafana/dashboards/isucon.json
      - ./grafana/log.json:/var/lib/grafana/dashboards/log.json
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
  pprotein:
    build: ./pprotein
    ports:
      - '49000:9000'
    volumes:
      - pprotein:/app/data
  adminer:
    image: adminer:latest
    ports:
      - '48080:8080'
  loki:
    image: grafana/loki:latest
    ports:
      - '43100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    restart: always

  #ポートフォワーディング用のコンテナ
  s1:
    build: ./tunnel
    volumes:
      - ./tunnel/config:/etc/ssh/ssh_config:ro
    command: -N s1
    restart: always
    develop:
      watch:
        - path: ./tunnel/config
          action: rebuild
  s2:
    build: ./tunnel
    volumes:
      - ./tunnel/config:/etc/ssh/ssh_config:ro
    command: -N s2
    restart: always
    develop:
      watch:
        - path: ./tunnel/config
          action: rebuild
volumes:
  grafana:
  pprotein:
